### ISSUE TITLE
[1x2h (2x3h)] - font size

### ISSUE THREAD

**Issue by malte-b** [hpi-swa-teaching/SWT18-Project-08#7]
# Story
As a user I want to change the text size of my words to be more flexible in designing my document.

 - [x] apply Pheno font size whole text component
 - [x] change UI to Icon only buttons
 - [x] call `small` on Buttons?
 - [x] make fontSizeField only accept up to two integers

**Comment by adrianjost** [comment]
Issues found:
1. can't press `del` (`entf`) Button
2. can't override - when 2 digits already there, I select the first one and try to write a new number to replace it -> should work! Test if there is an selection, if so allow typing even if there are already the maximum number of digits entered
3. allow 3 digits, I fell really limited with only 2 digits allowed.
4. Move menu to the component menu, because it's applied to the component, not the selection

**Comment by malte-b** [comment]
Would be nice if you could write the issues in the pull request instead of here.

**Comment by adrianjost** [comment]
Will do so, but there wasn't an pull opened when I wrote this @malte-b Will copy it now
